stages:
    - build
    - test
    - push
    - deploy

variables:
    OWNER_NAME: "Muhammad Fahad"

build_job:
    stage: build
    script: 
        - echo "This build is done using docker by $OWNER_NAME"
    tags:
        - dev


test_job:
    stage: test
    script:
        - echo "This is testing for docker build"
    tags:
        - dev

push_job:
    stage: push
    script:
        - echo "This is pushing to docker-hub"
    tags:
        - dev

deploy_job:
    stage: deploy
    script:
        - echo "Deploy to EC2 instance is going on"
    tags:
        - dev

production_test_job:
    stage: test
    script:
    - mkdir -p logs
    - echo "Testing..." > logs/test.log
    artifacts:
        paths:
            - logs/
        expire_in: 1 hour
    tags:
        - dev