stages:
    - build
    - test
    - push
    - deploy


build_job:
    stage: build
    script: 
        docker build -t flask-app:latest .
    tags:
        - dev


test_job:
    stage: test
    script:
        - echo "This is testing......."
    tags:
        - dev

push_job:
    stage: push
    script:
        - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        - docker image tag flask-app:latest $DOCKERHUB_USERNAME/flask-app:latest
        - docker push $DOCKERHUB_USERNAME/flask-app:latest
    tags:
        - dev

deploy_job:
    stage: deploy
    script:
        - docker-compose up -d
    tags:
        - dev
