stages:
    - build
    - test
    - push
    - deploy

variables:
    OWNER_NAME: "Muhammad Fahad"

build_job:
    stage: build
    script: 
        - echo "This build is done using docker by $OWNER_NAME"


test_job:
    stage: test
    script:
        - echo "This is testing for docker build"

push_job:
    stage: push
    script:
        - echo "This is pushing to docker-hub"

deploy_job:
    stage: deploy
    script:
        - echo "Deploy to EC2 instance is going on"

production_test_job:
    stage: test
    script:
    - mkdir -p logs
    - echo "Testing..." > logs/test.log
    artifacts:
        paths:
            - logs/